name: Deep Harmony
version: "2.6"
panel_icon: "mdi:cctv"
panel_title: Deep Harmony
slug: deepharmony
description: A Roon Extension for Logitech Harmony
url: "https://github.com/Khazul/roon-extension-deep-harmony-release"
startup: application
boot: auto
panel_admin: false
host_network: true
full_access: false
options: {}
schema: {}
arch:
  - amd64
  - armv7
  - aarch64