name: Deep Harmony
version: "2.6.0"
apparmor: false
panel_icon: "mdi:music"
panel_title: Deep Harmony
slug: deepharmony
description: A Roon Extension for Logitech Harmony
url: "https://github.com/Khazul/roon-extension-deep-harmony-release"
startup: application
boot: auto
panel_admin: false
host_network: true
full_access: false
webui: http://[HOST]:[PORT:9080]/console
options: {}
schema: false
arch:
  - amd64
  - armv7
  - aarch64