name: "Deep Harmony"
version: "2.6.7"
slug: "deepharmony"
description: "A Roon Extension for Logitech Harmony"
webui: "http://[HOST]:[PORT:9080]/console"
arch:
  - amd64
  - i386
startup: application
boot: auto
hassio_api: true
host_network: true