import os
import sys
import paho.mqtt.publish as publish

MQTTBROKERHOST = sys.argv[1]
MQTTBROKERPORT = int(sys.argv[2])
MQTTUSERNAME = sys.argv[3]
MQTTPASSWORD = sys.argv[4]

msgs = []
print("starting Davis Sensor MQTT Autodiscovery")
msgs.append({'topic': "homeassistant/sensor/davispro/barometer/config", 'payload':"{\"name\":\"Barometer\",\"device_class\":\"pressure\",\"platform\":\"mqtt\",\"state_topic\":\"/davis/wflrtd.json\",\"unit_of_measurement\":\"mbar\",\"value_template\":\"{{ (float(value_json.bar) * 33.8639) | round(1) }}\",\"icon\":\"mdi:gauge\"}",'retain':True})
msgs.append({'topic': "homeassistant/sensor/davispro/windspeedhightime/config", 'payload':"{\"name\":\"Hoogste Windsnelheid Tijd\",\"platform\":\"mqtt\",\"state_topic\":\"/davis/wflhilow.json\",\"value_template\":\"{{ value_json.hlwind[0] }}\"}",'retain':True})
msgs.append({'topic': "homeassistant/sensor/davispro/windspeedhigh/config", 'payload':"{\"name\":\"Hoogste Windsnelheid\",\"platform\":\"mqtt\",\"state_topic\":\"/davis/wflhilow.json\",\"unit_of_measurement\":\"km/h\",\"value_template\":\"{{ (float(value_json.hlwind[1]) * 1.609344) | round(0) }}\",\"icon\":\"mdi:weather-windy\"}",'retain':True})
msgs.append({'topic': "homeassistant/sensor/davispro/moisturehightime/config", 'payload':"{\"name\":\"Hoogste Luchtvochtigheid Tijd\",\"platform\":\"mqtt\",\"state_topic\":\"/davis/wflhilow.json\",\"value_template\":\"{{ value_json.hlhumout[2] }}\"}",'retain':True})
msgs.append({'topic': "homeassistant/sensor/davispro/moisturehigh/config", 'payload':"{\"name\":\"Hoogste Luchtvochtigheid\",\"device_class\":\"humidity\",\"platform\":\"mqtt\",\"state_topic\":\"/davis/wflhilow.json\",\"unit_of_measurement\":\"%\",\"value_template\":\"{{ value_json.hlhumout[3] }}\",\"icon\":\"mdi:water-percent\"}",'retain':True})
msgs.append({'topic': "homeassistant/sensor/davispro/temphightime/config", 'payload':"{\"name\":\"Hoogste Temperatuur Tijd\",\"platform\":\"mqtt\",\"state_topic\":\"/davis/wflhilow.json\",\"value_template\":\"{{ value_json.hltempout[2] }}\"}",'retain':True})
msgs.append({'topic': "homeassistant/sensor/davispro/temphigh/config", 'payload':"{\"name\":\"Hoogste Temperatuur\",\"device_class\":\"temperature\",\"platform\":\"mqtt\",\"state_topic\":\"/davis/wflhilow.json\",\"unit_of_measurement\":\"°F\",\"value_template\":\"{{ value_json.hltempout[3] }}\",\"icon\":\"mdi:weather-windy\"}",'retain':True})
msgs.append({'topic': "homeassistant/sensor/davispro/moisturelowtime/config", 'payload':"{\"name\":\"Laagste Luchtvochtigheid Tijd\",\"platform\":\"mqtt\",\"state_topic\":\"/davis/wflhilow.json\",\"value_template\":\"{{ value_json.hlhumout[0] }}\"}",'retain':True})
msgs.append({'topic': "homeassistant/sensor/davispro/moisturelow/config", 'payload':"{\"name\":\"Laagste Luchtvochtigheid\",\"device_class\":\"humidity\",\"platform\":\"mqtt\",\"state_topic\":\"/davis/wflhilow.json\",\"unit_of_measurement\":\"%\",\"value_template\":\"{{ value_json.hlhumout[1] }}\",\"icon\":\"mdi:water-percent\"}",'retain':True})
msgs.append({'topic': "homeassistant/sensor/davispro/chill/config", 'payload':"{\"name\":\"Gevoelstemperatuur\",\"device_class\":\"temperature\",\"platform\":\"mqtt\",\"state_topic\":\"/davis/wflrtd.json\",\"unit_of_measurement\":\"°F\",\"value_template\":\"{{ value_json.chill }}\",\"icon\":\"mdi:thermometer\"}",'retain':True})
msgs.append({'topic': "homeassistant/sensor/davispro/dewpoint/config", 'payload':"{\"name\":\"Dauwpunt\",\"device_class\":\"temperature\",\"platform\":\"mqtt\",\"state_topic\":\"/davis/wflrtd.json\",\"unit_of_measurement\":\"°F\",\"value_template\":\"{{ value_json.cdew }}\",\"icon\":\"mdi:thermometer\"}",'retain':True})
msgs.append({'topic': "homeassistant/sensor/davispro/templowtime/config", 'payload':"{\"name\":\"Laagste Temperatuur Tijd\",\"platform\":\"mqtt\",\"state_topic\":\"/davis/wflhilow.json\",\"value_template\":\"{{ value_json.hltempout[0] }}\"}",'retain':True})
msgs.append({'topic': "homeassistant/sensor/davispro/templow/config", 'payload':"{\"name\":\"Laagste Temperatuur\",\"device_class\":\"temperature\",\"platform\":\"mqtt\",\"state_topic\":\"/davis/wflhilow.json\",\"unit_of_measurement\":\"°F\",\"value_template\":\"{{ value_json.hltempout[1]}}\",\"icon\":\"mdi:weather-windy\"}",'retain':True})
msgs.append({'topic': "homeassistant/sensor/davispro/moisture/config", 'payload':"{\"name\":\"Luchtvochtigheid\",\"device_class\":\"humidity\",\"platform\":\"mqtt\",\"state_topic\":\"/davis/wflrtd.json\",\"unit_of_measurement\":\"%\",\"value_template\":\"{{ value_json.humout }}\",\"icon\":\"mdi:water-percent\"}",'retain':True})
msgs.append({'topic': "homeassistant/sensor/davispro/temp/config", 'payload':"{\"name\":\"Buitentemperatuur\",\"device_class\":\"temperature\",\"platform\":\"mqtt\",\"state_topic\":\"/davis/wflrtd.json\",\"unit_of_measurement\":\"°F\",\"value_template\":\"{{ value_json.tempout }}\",\"icon\":\"mdi:thermometer\"}",'retain':True})
msgs.append({'topic': "homeassistant/sensor/davispro/rain/config", 'payload':"{\"name\":\"Regenhoveelheid\",\"platform\":\"mqtt\",\"state_topic\":\"/davis/wflrtd.json\",\"unit_of_measurement\":\"mm/h\",\"value_template\":\"{{ (float(value_json.rainr) * 25.4) | round(1) }}\",\"icon\":\"mdi:weather-rainy\"}",'retain':True})
msgs.append({'topic': "homeassistant/sensor/davispro/rainhour/config", 'payload':"{\"name\":\"Regenhoveelheid Uur\",\"platform\":\"mqtt\",\"state_topic\":\"/davis/wflrtd.json\",\"unit_of_measurement\":\"mm\",\"value_template\":\"{{ (float(value_json.rain1h) * 25.4) | round(1) }}\",\"icon\":\"mdi:weather-rainy\"}",'retain':True})
msgs.append({'topic': "homeassistant/sensor/davispro/rainday/config", 'payload':"{\"name\":\"Regenhoveelheid Dag\",\"platform\":\"mqtt\",\"state_topic\":\"/davis/wflrtd.json\",\"unit_of_measurement\":\"mm\",\"value_template\":\"{{ (float(value_json.raind) * 25.4) | round(1) }}\",\"icon\":\"mdi:weather-rainy\"}",'retain':True})
msgs.append({'topic': "homeassistant/sensor/davispro/rainmonth/config", 'payload':"{\"name\":\"Regenhoveelheid Maand\",\"platform\":\"mqtt\",\"state_topic\":\"/davis/wflrtd.json\",\"unit_of_measurement\":\"mm\",\"value_template\":\"{{ (float(value_json.rainmon) * 25.4) | round(1) }}\",\"icon\":\"mdi:weather-rainy\"}",'retain':True})
msgs.append({'topic': "homeassistant/sensor/davispro/rainyear/config", 'payload':"{\"name\":\"Regenhoveelheid Jaar\",\"platform\":\"mqtt\",\"state_topic\":\"/davis/wflrtd.json\",\"unit_of_measurement\":\"mm\",\"value_template\":\"{{ (float(value_json.rainyear) * 25.4) | round(1) }}\",\"icon\":\"mdi:weather-rainy\"}",'retain':True})
msgs.append({'topic': "homeassistant/sensor/davispro/solar/config", 'payload':"{\"name\":\"Zonnestraling\",\"platform\":\"mqtt\",\"state_topic\":\"/davis/wflrtd.json\",\"unit_of_measurement\":\"W/m²\",\"value_template\":\"{{ value_json.solar }}\",\"icon\":\"mdi:white-balance-sunny\"}",'retain':True})
msgs.append({'topic': "homeassistant/sensor/davispro/et/config", 'payload':"{\"name\":\"Verdamping\",\"platform\":\"mqtt\",\"state_topic\":\"/davis/wflrtd.json\",\"unit_of_measurement\":\"mm\",\"value_template\":\"{{ (float(value_json.etday) * 25.4) | round(3) }}\",\"icon\":\"mdi:weather-sunset-up\"}",'retain':True})
msgs.append({'topic': "homeassistant/sensor/davispro/uvindex/config", 'payload':"{\"name\":\"UV Index\",\"platform\":\"mqtt\",\"state_topic\":\"/davis/wflrtd.json\",\"unit_of_measurement\":\"index\",\"value_template\":\"{{ value_json.uv }}\",\"icon\":\"mdi:weather-sunny\"}",'retain':True})
msgs.append({'topic': "homeassistant/sensor/davispro/winddirection/config", 'payload':"{\"name\":\"Windrichting\",\"platform\":\"mqtt\",\"state_topic\":\"/davis/wflrtd.json\",\"unit_of_measurement\":\"°\",\"value_template\":\"{{ value_json.winddir }}\",\"icon\":\"mdi:compass\"}",'retain':True})
msgs.append({'topic': "homeassistant/sensor/davispro/windspeed/config", 'payload':"{\"name\":\"Windsnelheid\",\"platform\":\"mqtt\",\"state_topic\":\"/davis/wflrtd.json\",\"unit_of_measurement\":\"km/h\",\"value_template\":\"{{ (float(value_json.windspd) * 1.609344) | round(0) }}\",\"icon\":\"mdi:weather-windy\"}",'retain':True})
msgs.append({'topic': "homeassistant/sensor/davispro/windspeedaverage/config", 'payload':"{\"name\":\"Windsnelheid Gemiddeld\",\"platform\":\"mqtt\",\"state_topic\":\"/davis/wflrtd.json\",\"unit_of_measurement\":\"km/h\",\"value_template\":\"{{ (float(value_json.windavg2) * 1.609344) | round(0) }}\",\"icon\":\"mdi:weather-windy\"}",'retain':True})
publish.multiple(msgs, hostname=MQTTBROKERHOST, port=MQTTBROKERPORT, auth={'username':MQTTUSERNAME, 'password':MQTTPASSWORD})

print("Ending Davis Sensor MQTT Autodiscovery. Notning to do here: exiting..")